export const POST_REQUEST = "POST_REQUEST";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_ERROR = "POST_ERROR";

export const LIST_POST_REQUEST = "LIST_POST_REQUEST";
export const LIST_POST_SUCCESS = "LIST_POST_SUCCESS";
export const LIST_POST_ERROR = "LIST_POST_ERROR";

export const LIST_USER_REQUEST = "LIST_USER_REQUEST";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const LIST_USER_ERROR = "LIST_USER_ERROR";
